//! Deterministic in-memory Pi RPC stand-in for adapter and supervisor tests.
//!
//! It is deliberately not a process launcher. Its only output is scripted
//! protocol bytes/events, so it cannot execute a command or contact Pi.

use crate::codec::{NormalizedRpcEvent, RpcCodec, RpcCodecConfig, RpcEventNormalizer};
use piui_contracts::{ProjectId, RuntimeEvent, RuntimeId, RuntimeState, RuntimeStateEvent};
use serde_json::{Map, Value, json};
use thiserror::Error;

const FAKE_TRANSPORT_CHUNK_BYTES: usize = 17;
const MAX_FAKE_TRANSPORT_FRAME_BYTES: usize = 32 * 1024;
const MAX_FAKE_TRANSPORT_EVENTS: usize = 64;
const MAX_FAKE_EVENT_TEXT_CHARS: usize = 4_000;
const MAX_FAKE_IDENTIFIER_CHARS: usize = 128;
const FAKE_RPC_TYPES: [&str; 4] = [
    "turn.started",
    "message.text.delta",
    "turn.completed",
    "abort.acknowledged",
];

/// Uses the versioned host/UI lifecycle state from `piui-contracts`.
/// The fake cannot report process handles, paths, or raw diagnostics.
pub type LifecycleState = RuntimeState;

/// Fixed behaviours intentionally covering normal and failure protocol paths.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FakeScenario {
    /// A complete assistant turn with deterministic delta ordering.
    Stream,
    /// Leaves the turn running until an abort command is received.
    Abort,
    /// Simulates a process crash during a turn, followed by EOF.
    Crash,
    /// Emits invalid JSONL and then fails the runtime.
    Malformed,
}

/// Minimal raw RPC commands understood by this test double.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FakeCommand {
    Prompt { command_id: String, text: String },
    Abort { command_id: String },
    Stop,
}

/// Observable output from a fake runtime step.
#[derive(Debug, Clone, PartialEq)]
pub enum FakeEmission {
    /// A host-safe lifecycle event using the shared contract DTO.
    Contract(Box<RuntimeEvent>),
    /// A valid decoded Pi-RPC-like object. Call [`FakeEmission::jsonl_bytes`]
    /// to send it through the actual byte codec.
    Rpc(Value),
    /// Raw deliberately-invalid stdout bytes, used only by `Malformed`.
    MalformedBytes(Vec<u8>),
    /// The stdout source ended. A supervisor must call codec `finish`.
    Eof,
}

impl FakeEmission {
    /// Renders one RPC event to JSONL. State/EOF emissions do not have an RPC
    /// line and malformed emissions retain their exact bytes.
    pub fn jsonl_bytes(&self) -> Result<Option<Vec<u8>>, FakeRuntimeError> {
        match self {
            Self::Contract(_) | Self::Eof => Ok(None),
            Self::MalformedBytes(bytes) => Ok(Some(bytes.clone())),
            Self::Rpc(value) => {
                let mut bytes = serde_json::to_vec(value)
                    .map_err(|error| FakeRuntimeError::Serialization(error.to_string()))?;
                bytes.push(b'\n');
                Ok(Some(bytes))
            }
        }
    }
}

/// Safe, normalized output from the deterministic fake's simulated stdout.
/// Unknown RPC input remains payload-free, exactly as it must for a future
/// process transport. This type never contains command IDs, block IDs,
/// revisions, raw frames, filesystem locations, or credentials.
#[derive(Debug, Clone, PartialEq)]
pub enum FakeTransportEvent {
    /// A local lifecycle transition generated by the fake host state machine,
    /// not by the simulated stdout pipe.
    Contract(Box<RuntimeEvent>),
    TurnStarted,
    MessageTextDelta {
        text: String,
    },
    TurnCompleted,
    AbortAcknowledged,
    Unknown(crate::OpaqueRpcEvent),
}

/// Path-free failures while replaying deterministic fake stdout through the
/// same LF JSONL transport boundary intended for a future contained runtime.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum FakeTransportError {
    #[error("fake runtime transport frame encoding failed")]
    FrameEncoding,
    #[error("fake runtime transport rejected a protocol frame")]
    Protocol,
    #[error("fake runtime transport rejected a known event shape")]
    InvalidKnownEvent,
    #[error("fake runtime transport is terminal after a protocol failure")]
    Terminal,
    #[error("fake runtime transport received output after EOF")]
    OutputAfterEof,
    #[error("fake runtime transport exceeded its fixed event budget")]
    EventLimit,
}

/// Deterministic, non-spawning replay adapter for fake stdout. Every fake RPC
/// emission is encoded to bytes, split into arbitrary-sized chunks, decoded by
/// [`RpcCodec`], normalized through [`RpcEventNormalizer`], and then strictly
/// shape-checked before state is retained. It never opens a pipe or process.
#[derive(Debug)]
pub struct FakeTransportReplay {
    codec: RpcCodec,
    normalizer: RpcEventNormalizer,
    events: Vec<FakeTransportEvent>,
    saw_eof: bool,
    terminal: bool,
}

impl Default for FakeTransportReplay {
    fn default() -> Self {
        Self::new()
    }
}

impl FakeTransportReplay {
    #[must_use]
    pub fn new() -> Self {
        // The default frame limit is a fixed nonzero crate constant, so this
        // construction cannot fail. Keeping the codec construction here makes
        // the fake exercise the production framing path rather than Values.
        let codec = RpcCodec::new(RpcCodecConfig::new(MAX_FAKE_TRANSPORT_FRAME_BYTES))
            .expect("fixed fake transport codec configuration is always valid");
        Self {
            codec,
            normalizer: RpcEventNormalizer::new(FAKE_RPC_TYPES),
            events: Vec::new(),
            saw_eof: false,
            terminal: false,
        }
    }

    /// Replays an ordered deterministic fake emission sequence. Valid events
    /// accepted before a later protocol failure remain available through
    /// [`Self::events`], which lets the UI render only confirmed output before
    /// showing a safe transport-failure notice.
    pub fn replay<I>(&mut self, emissions: I) -> Result<(), FakeTransportError>
    where
        I: IntoIterator<Item = FakeEmission>,
    {
        for emission in emissions {
            self.push_emission(emission)?;
        }
        Ok(())
    }

    /// Returns only normalized, safe fake transport observations.
    #[must_use]
    pub fn events(&self) -> &[FakeTransportEvent] {
        &self.events
    }

    /// Whether an EOF was accepted by the LF codec. EOF is meaningful only
    /// after [`RpcCodec::finish`] confirms there is no unterminated frame.
    #[must_use]
    pub const fn saw_eof(&self) -> bool {
        self.saw_eof
    }

    fn push_emission(&mut self, emission: FakeEmission) -> Result<(), FakeTransportError> {
        if self.terminal {
            return Err(FakeTransportError::Terminal);
        }
        if self.saw_eof {
            return self.fail(FakeTransportError::OutputAfterEof);
        }
        match emission {
            FakeEmission::Contract(event) => self.push_event(FakeTransportEvent::Contract(event)),
            FakeEmission::Eof => {
                if self.codec.finish().is_err() {
                    return self.fail(FakeTransportError::Protocol);
                }
                self.saw_eof = true;
                Ok(())
            }
            emission @ (FakeEmission::Rpc(_) | FakeEmission::MalformedBytes(_)) => {
                let bytes = match emission.jsonl_bytes() {
                    Ok(Some(bytes)) => bytes,
                    Ok(None) | Err(_) => return self.fail(FakeTransportError::FrameEncoding),
                };
                for chunk in bytes.chunks(FAKE_TRANSPORT_CHUNK_BYTES) {
                    let values = match self.codec.push(chunk) {
                        Ok(values) => values,
                        Err(_) => return self.fail(FakeTransportError::Protocol),
                    };
                    for value in values {
                        self.accept_value(value)?;
                    }
                }
                Ok(())
            }
        }
    }

    fn accept_value(&mut self, value: Value) -> Result<(), FakeTransportError> {
        let event = match self.normalizer.normalize(value) {
            NormalizedRpcEvent::Unknown(event) => FakeTransportEvent::Unknown(event),
            NormalizedRpcEvent::Known { event_type, value } => {
                match validate_known_fake_event(&event_type, &value) {
                    Ok(event) => event,
                    Err(error) => return self.fail(error),
                }
            }
        };
        self.push_event(event)
    }

    fn push_event(&mut self, event: FakeTransportEvent) -> Result<(), FakeTransportError> {
        if self.events.len() >= MAX_FAKE_TRANSPORT_EVENTS {
            return self.fail(FakeTransportError::EventLimit);
        }
        self.events.push(event);
        Ok(())
    }

    fn fail<T>(&mut self, error: FakeTransportError) -> Result<T, FakeTransportError> {
        self.terminal = true;
        Err(error)
    }
}

fn validate_known_fake_event(
    event_type: &str,
    value: &Value,
) -> Result<FakeTransportEvent, FakeTransportError> {
    let Some(object) = value.as_object() else {
        return Err(FakeTransportError::InvalidKnownEvent);
    };
    match event_type {
        "turn.started" => {
            require_identifier(object, "commandId")?;
            require_positive_revision(object)?;
            Ok(FakeTransportEvent::TurnStarted)
        }
        "message.text.delta" => {
            require_identifier(object, "blockId")?;
            require_positive_revision(object)?;
            let Some(text) = object.get("text").and_then(Value::as_str) else {
                return Err(FakeTransportError::InvalidKnownEvent);
            };
            if text.chars().count() > MAX_FAKE_EVENT_TEXT_CHARS
                || text.chars().any(char::is_control)
            {
                return Err(FakeTransportError::InvalidKnownEvent);
            }
            Ok(FakeTransportEvent::MessageTextDelta {
                text: text.to_owned(),
            })
        }
        "turn.completed" => {
            require_identifier(object, "commandId")?;
            require_positive_revision(object)?;
            if !matches!(
                object.get("stopReason").and_then(Value::as_str),
                Some("complete" | "aborted")
            ) {
                return Err(FakeTransportError::InvalidKnownEvent);
            }
            Ok(FakeTransportEvent::TurnCompleted)
        }
        "abort.acknowledged" => {
            require_identifier(object, "commandId")?;
            require_positive_revision(object)?;
            Ok(FakeTransportEvent::AbortAcknowledged)
        }
        // `RpcEventNormalizer` owns the allowlist; this is intentionally a
        // fail-closed guard if the two lists ever diverge.
        _ => Err(FakeTransportError::InvalidKnownEvent),
    }
}

fn require_identifier(object: &Map<String, Value>, field: &str) -> Result<(), FakeTransportError> {
    let Some(value) = object.get(field).and_then(Value::as_str) else {
        return Err(FakeTransportError::InvalidKnownEvent);
    };
    if value.is_empty()
        || value.chars().count() > MAX_FAKE_IDENTIFIER_CHARS
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'_' | b'-'))
    {
        return Err(FakeTransportError::InvalidKnownEvent);
    }
    Ok(())
}

fn require_positive_revision(object: &Map<String, Value>) -> Result<(), FakeTransportError> {
    match object.get("revision").and_then(Value::as_u64) {
        Some(revision) if revision > 0 => Ok(()),
        _ => Err(FakeTransportError::InvalidKnownEvent),
    }
}

#[derive(Debug, Error, Clone, PartialEq, Eq)]
pub enum FakeRuntimeError {
    #[error("cannot {action} while fake runtime is {state}")]
    InvalidTransition {
        action: &'static str,
        state: &'static str,
    },
    #[error("cannot abort without a running turn")]
    AbortWithoutRunningTurn,
    #[error("fake JSON serialization failed: {0}")]
    Serialization(String),
}

/// A deterministic, non-spawning lifecycle machine.
#[derive(Debug)]
pub struct FakeRuntime {
    scenario: FakeScenario,
    state: LifecycleState,
    revision: u64,
    active_turn: Option<String>,
}

impl FakeRuntime {
    #[must_use]
    pub const fn new(scenario: FakeScenario) -> Self {
        Self {
            scenario,
            state: RuntimeState::Dormant,
            revision: 0,
            active_turn: None,
        }
    }

    #[must_use]
    pub const fn state(&self) -> LifecycleState {
        self.state
    }

    #[must_use]
    pub const fn revision(&self) -> u64 {
        self.revision
    }

    /// Starts the fake runtime. Startup is deliberately synchronous and
    /// repeatable: `Dormant -> Starting -> Ready`.
    pub fn start(&mut self) -> Result<Vec<FakeEmission>, FakeRuntimeError> {
        if self.state != RuntimeState::Dormant {
            return Err(self.invalid("start"));
        }
        let starting = self.transition(RuntimeState::Starting, None);
        let ready = self.transition(RuntimeState::Ready, None);
        Ok(vec![starting, ready])
    }

    /// Applies a single command in arrival order. No command is queued or
    /// executed outside the allowed lifecycle transition.
    pub fn command(&mut self, command: FakeCommand) -> Result<Vec<FakeEmission>, FakeRuntimeError> {
        match command {
            FakeCommand::Prompt { command_id, text } => self.prompt(command_id, text),
            FakeCommand::Abort { command_id } => self.abort(command_id),
            FakeCommand::Stop => self.stop(),
        }
    }

    fn prompt(
        &mut self,
        command_id: String,
        text: String,
    ) -> Result<Vec<FakeEmission>, FakeRuntimeError> {
        if self.state != RuntimeState::Ready {
            return Err(self.invalid("prompt"));
        }

        self.active_turn = Some(command_id.clone());
        let mut emissions = vec![self.transition(RuntimeState::Running, None)];
        emissions.push(FakeEmission::Rpc(json!({
            "type": "turn.started",
            "commandId": command_id,
            "revision": self.next_revision(),
        })));

        match self.scenario {
            FakeScenario::Stream => {
                emissions.push(FakeEmission::Rpc(json!({
                    "type": "message.text.delta",
                    "blockId": "assistant-1",
                    "text": "deterministic ",
                    "revision": self.next_revision(),
                })));
                emissions.push(FakeEmission::Rpc(json!({
                    "type": "message.text.delta",
                    "blockId": "assistant-1",
                    "text": text,
                    "revision": self.next_revision(),
                })));
                emissions.push(FakeEmission::Rpc(json!({
                    "type": "turn.completed",
                    "commandId": command_id,
                    "stopReason": "complete",
                    "revision": self.next_revision(),
                })));
                self.active_turn = None;
                emissions.push(self.transition(RuntimeState::Ready, None));
            }
            FakeScenario::Abort => {
                emissions.push(FakeEmission::Rpc(json!({
                    "type": "message.text.delta",
                    "blockId": "assistant-1",
                    "text": "waiting for abort",
                    "revision": self.next_revision(),
                })));
            }
            FakeScenario::Crash => {
                emissions.push(FakeEmission::Rpc(json!({
                    "type": "message.text.delta",
                    "blockId": "assistant-1",
                    "text": "before crash",
                    "revision": self.next_revision(),
                })));
                self.active_turn = None;
                emissions.push(self.transition(RuntimeState::Failed, Some("process-crash")));
                emissions.push(FakeEmission::Eof);
            }
            FakeScenario::Malformed => {
                emissions.push(FakeEmission::MalformedBytes(b"{not-json}\n".to_vec()));
                self.active_turn = None;
                emissions.push(self.transition(RuntimeState::Failed, Some("malformed-rpc")));
                emissions.push(FakeEmission::Eof);
            }
        }
        Ok(emissions)
    }

    fn abort(&mut self, command_id: String) -> Result<Vec<FakeEmission>, FakeRuntimeError> {
        if self.state != RuntimeState::Running || self.active_turn.is_none() {
            return Err(FakeRuntimeError::AbortWithoutRunningTurn);
        }
        let mut emissions = vec![FakeEmission::Rpc(json!({
            "type": "abort.acknowledged",
            "commandId": command_id,
            "revision": self.next_revision(),
        }))];
        let Some(turn_id) = self.active_turn.take() else {
            return Err(FakeRuntimeError::AbortWithoutRunningTurn);
        };
        emissions.push(FakeEmission::Rpc(json!({
            "type": "turn.completed",
            "commandId": turn_id,
            "stopReason": "aborted",
            "revision": self.next_revision(),
        })));
        emissions.push(self.transition(RuntimeState::Ready, Some("aborted")));
        Ok(emissions)
    }

    fn stop(&mut self) -> Result<Vec<FakeEmission>, FakeRuntimeError> {
        match self.state {
            RuntimeState::Ready | RuntimeState::Running | RuntimeState::Failed => {
                let mut emissions =
                    vec![self.transition(RuntimeState::Stopping, Some("stop-requested"))];
                self.active_turn = None;
                emissions.push(self.transition(RuntimeState::Dormant, Some("stopped")));
                emissions.push(FakeEmission::Eof);
                Ok(emissions)
            }
            _ => Err(self.invalid("stop")),
        }
    }

    fn transition(
        &mut self,
        current: LifecycleState,
        reason: Option<&'static str>,
    ) -> FakeEmission {
        let previous = self.state;
        self.state = current;
        FakeEmission::Contract(Box::new(RuntimeEvent::State(RuntimeStateEvent {
            runtime_id: RuntimeId::from("fake-runtime"),
            project_id: ProjectId::from("fake-project"),
            session_id: None,
            state: current,
            previous_state: Some(previous),
            reason_code: reason.map(str::to_owned),
            safe_summary: reason.map(|_| "Deterministic fake runtime transition.".to_owned()),
        })))
    }

    fn next_revision(&mut self) -> u64 {
        self.revision = self.revision.saturating_add(1);
        self.revision
    }

    fn invalid(&self, action: &'static str) -> FakeRuntimeError {
        FakeRuntimeError::InvalidTransition {
            action,
            state: state_label(self.state),
        }
    }
}

fn state_label(state: RuntimeState) -> &'static str {
    match state {
        RuntimeState::Dormant => "dormant",
        RuntimeState::Starting => "starting",
        RuntimeState::Ready => "ready",
        RuntimeState::Running => "running",
        RuntimeState::Recovering => "recovering",
        RuntimeState::Stopping => "stopping",
        RuntimeState::Failed => "failed",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codec::{RpcCodec, RpcCodecConfig, RpcCodecError};

    fn start_ready(runtime: &mut FakeRuntime) {
        let states: Vec<_> = runtime
            .start()
            .expect("start fake")
            .into_iter()
            .filter_map(|emission| match emission {
                FakeEmission::Contract(event) => match event.as_ref() {
                    RuntimeEvent::State(state) => Some(state.state),
                    RuntimeEvent::Snapshot(_) => None,
                },
                _ => None,
            })
            .collect();
        assert_eq!(states, [RuntimeState::Starting, RuntimeState::Ready]);
    }

    #[test]
    fn stream_is_ordered_and_returns_to_ready() {
        let mut runtime = FakeRuntime::new(FakeScenario::Stream);
        start_ready(&mut runtime);
        let emissions = runtime
            .command(FakeCommand::Prompt {
                command_id: "cmd-1".into(),
                text: "hello".into(),
            })
            .expect("stream command");
        let event_types: Vec<_> = emissions
            .iter()
            .filter_map(|emission| match emission {
                FakeEmission::Rpc(value) => value["type"].as_str(),
                _ => None,
            })
            .collect();
        assert_eq!(
            event_types,
            [
                "turn.started",
                "message.text.delta",
                "message.text.delta",
                "turn.completed"
            ]
        );
        assert_eq!(runtime.state(), RuntimeState::Ready);
        assert_eq!(runtime.revision(), 4);
    }

    #[test]
    fn abort_requires_running_turn_and_is_deterministic() {
        let mut runtime = FakeRuntime::new(FakeScenario::Abort);
        start_ready(&mut runtime);
        assert_eq!(
            runtime.command(FakeCommand::Abort {
                command_id: "abort-0".into()
            }),
            Err(FakeRuntimeError::AbortWithoutRunningTurn)
        );
        runtime
            .command(FakeCommand::Prompt {
                command_id: "turn-1".into(),
                text: "ignored".into(),
            })
            .expect("begins turn");
        let abort = runtime
            .command(FakeCommand::Abort {
                command_id: "abort-1".into(),
            })
            .expect("abort");
        assert!(matches!(
            abort.last(),
            Some(FakeEmission::Contract(event))
                if matches!(
                    event.as_ref(),
                    RuntimeEvent::State(RuntimeStateEvent {
                        state: RuntimeState::Ready,
                        reason_code: Some(reason),
                        ..
                    }) if reason == "aborted"
                )
        ));
        assert_eq!(runtime.state(), RuntimeState::Ready);
    }

    #[test]
    fn crash_and_malformed_exercise_failure_paths() {
        let mut crash = FakeRuntime::new(FakeScenario::Crash);
        start_ready(&mut crash);
        let crash_output = crash
            .command(FakeCommand::Prompt {
                command_id: "crash".into(),
                text: "x".into(),
            })
            .expect("crash is an expected scenario");
        assert!(matches!(crash_output.last(), Some(FakeEmission::Eof)));
        assert_eq!(crash.state(), RuntimeState::Failed);

        let mut malformed = FakeRuntime::new(FakeScenario::Malformed);
        start_ready(&mut malformed);
        let malformed_output = malformed
            .command(FakeCommand::Prompt {
                command_id: "bad".into(),
                text: "x".into(),
            })
            .expect("malformed output is expected");
        let mut codec = RpcCodec::new(RpcCodecConfig::new(1024)).expect("codec");
        let invalid = malformed_output
            .into_iter()
            .find_map(|emission| match emission {
                FakeEmission::MalformedBytes(bytes) => Some(codec.push(&bytes)),
                _ => None,
            })
            .expect("malformed bytes emitted");
        assert!(matches!(invalid, Err(RpcCodecError::InvalidJson { .. })));
        assert_eq!(malformed.state(), RuntimeState::Failed);
    }

    #[test]
    fn transport_replay_exercises_fragmented_lf_transport_and_clean_eof() {
        let mut runtime = FakeRuntime::new(FakeScenario::Stream);
        let mut emissions = runtime.start().expect("starts fake");
        emissions.extend(
            runtime
                .command(FakeCommand::Prompt {
                    command_id: "turn-1".into(),
                    text: "hello".into(),
                })
                .expect("streams fake turn"),
        );
        emissions.extend(
            runtime
                .command(FakeCommand::Stop)
                .expect("stops fake runtime"),
        );

        let mut replay = FakeTransportReplay::new();
        replay.replay(emissions).expect("replays framed output");
        assert!(replay.saw_eof());
        let text: String = replay
            .events()
            .iter()
            .filter_map(|event| match event {
                FakeTransportEvent::MessageTextDelta { text } => Some(text.as_str()),
                _ => None,
            })
            .collect();
        assert_eq!(text, "deterministic hello");
        assert!(
            replay
                .events()
                .iter()
                .any(|event| matches!(event, FakeTransportEvent::TurnStarted))
        );
        assert!(
            replay
                .events()
                .iter()
                .any(|event| matches!(event, FakeTransportEvent::TurnCompleted))
        );
    }

    #[test]
    fn transport_replay_fails_closed_for_bad_known_events_or_unterminated_eof() {
        let mut malformed_known = FakeTransportReplay::new();
        assert_eq!(
            malformed_known.replay([FakeEmission::MalformedBytes(
                b"{\"type\":\"message.text.delta\",\"blockId\":\"assistant-1\",\"revision\":1}\n"
                    .to_vec(),
            )]),
            Err(FakeTransportError::InvalidKnownEvent)
        );
        assert_eq!(
            malformed_known.replay([FakeEmission::Eof]),
            Err(FakeTransportError::Terminal)
        );

        let mut incomplete = FakeTransportReplay::new();
        assert_eq!(
            incomplete.replay([
                FakeEmission::MalformedBytes(b"{\"type\":\"turn.started\"".to_vec()),
                FakeEmission::Eof,
            ]),
            Err(FakeTransportError::Protocol)
        );
        assert!(!incomplete.saw_eof());
    }

    #[test]
    fn transport_replay_bounds_frame_and_event_growth() {
        let mut oversized = FakeTransportReplay::new();
        let mut bytes = vec![b'x'; MAX_FAKE_TRANSPORT_FRAME_BYTES + 1];
        bytes.push(b'\n');
        assert_eq!(
            oversized.replay([FakeEmission::MalformedBytes(bytes)]),
            Err(FakeTransportError::Protocol)
        );

        let mut event_limited = FakeTransportReplay::new();
        let emissions: Vec<_> = (0..=MAX_FAKE_TRANSPORT_EVENTS)
            .map(|_| FakeEmission::MalformedBytes(b"{\"type\":\"future.event\"}\n".to_vec()))
            .collect();
        assert_eq!(
            event_limited.replay(emissions),
            Err(FakeTransportError::EventLimit)
        );
        assert_eq!(event_limited.events().len(), MAX_FAKE_TRANSPORT_EVENTS);
    }

    #[test]
    fn transport_replay_keeps_unknown_payloads_opaque_and_rejects_late_output() {
        const SECRET: &str = "FAKE_TRANSPORT_SECRET_2af1c6";
        let mut replay = FakeTransportReplay::new();
        replay
            .replay([
                FakeEmission::MalformedBytes(
                    serde_json::to_vec(&json!({
                        "type": "future.event",
                        "prompt": SECRET,
                        "credentials": SECRET,
                    }))
                    .expect("serializes fixture")
                    .into_iter()
                    .chain(std::iter::once(b'\n'))
                    .collect(),
                ),
                FakeEmission::Eof,
            ])
            .expect("unknown event stays opaque");
        let output = format!("{:?}", replay.events());
        assert!(!output.contains(SECRET));
        assert!(matches!(replay.events(), [FakeTransportEvent::Unknown(_)]));
        assert_eq!(
            replay.replay([FakeEmission::Eof]),
            Err(FakeTransportError::OutputAfterEof)
        );
    }

    #[test]
    fn fake_module_retains_no_process_or_shell_surface() {
        let source = include_str!("fake.rs");
        for forbidden in [
            ["Command", "::new"].concat(),
            ["std", "::process::Command"].concat(),
            ["tokio", "::process"].concat(),
            ["std", "::fs"].concat(),
        ] {
            assert!(
                !source.contains(&forbidden),
                "fake transport must not contain {forbidden}"
            );
        }
    }
}
