import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const requireDesktop = createRequire(new URL('../apps/desktop/package.json', import.meta.url));
const Ajv = requireDesktop('ajv');
const standalone = requireDesktop('ajv/dist/standalone').default;
for (const version of [1, 2, 3, 4]) {
const schema = JSON.parse(readFileSync(new URL(`../contracts/system-file-v${version}.schema.json`, import.meta.url), 'utf8'));
const ajv = new Ajv({ allErrors: true, strict: true, code: { source: true, esm: true, lines: true } });
const code = `// Generated by pnpm system:schema. Do not edit; source: system-file-v${version}.schema.json.\n` + standalone(ajv, ajv.compile(schema)).trimEnd() + '\n';
// A runtime helper would be a CommonJS require in an ES module (for example
// maxLength needs Ajv's Unicode length helper): keep the schema free of it.
if (code.includes('require(')) throw new Error(`system-file-v${version}.schema.json needs an Ajv runtime helper; the validator must stay self-contained.`);
const target = new URL(`../contracts/system-file-v${version}-validator.mjs`, import.meta.url);
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== code) throw new Error('System schema validator is stale. Run pnpm system:schema.');
  console.log('System file schema validator is current.');
} else { writeFileSync(target, code); console.log('Generated CSP-safe system file validator.'); }

}
// Plugin package manifests v1 and v2 (ADR-032): the same CSP-safe standalone
// form. Ajv's Unicode length helper is inlined so the module stays
// self-contained and counts code points like the Rust host.
for (const version of [1, 2]) {
  const schema = JSON.parse(readFileSync(new URL(`../contracts/piui-plugin-v${version}.schema.json`, import.meta.url), 'utf8'));
  const ajv = new Ajv({ allErrors: true, strict: true, code: { source: true, esm: true, lines: true } });
  const code = (`// Generated by pnpm system:schema. Do not edit; source: piui-plugin-v${version}.schema.json.\n` + standalone(ajv, ajv.compile(schema)).trimEnd() + '\n')
    .replace(/const (func\d+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/g, 'const $1 = (value) => [...value].length;');
  if (code.includes('require(')) throw new Error('The plugin manifest validator must not require runtime modules.');
  const target = new URL(`../contracts/piui-plugin-v${version}-validator.mjs`, import.meta.url);
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== code) throw new Error('Plugin manifest validator is stale. Run pnpm system:schema.');
    console.log('Plugin manifest schema validator is current.');
  } else { writeFileSync(target, code); console.log('Generated CSP-safe plugin manifest validator.'); }
}
