import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const requireDesktop = createRequire(new URL('../apps/desktop/package.json', import.meta.url));
const Ajv = requireDesktop('ajv');
const standalone = requireDesktop('ajv/dist/standalone').default;
for (const version of [1, 2, 3]) {
const schema = JSON.parse(readFileSync(new URL(`../contracts/system-file-v${version}.schema.json`, import.meta.url), 'utf8'));
const ajv = new Ajv({ allErrors: true, strict: true, code: { source: true, esm: true, lines: true } });
const code = `// Generated by pnpm system:schema. Do not edit; source: system-file-v${version}.schema.json.\n` + standalone(ajv, ajv.compile(schema)) + '\n';
const target = new URL(`../contracts/system-file-v${version}-validator.mjs`, import.meta.url);
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== code) throw new Error('System schema validator is stale. Run pnpm system:schema.');
  console.log('System file schema validator is current.');
} else { writeFileSync(target, code); console.log('Generated CSP-safe system file validator.'); }

}
